<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <img src="xxxxxx.jpg" alt="">
</body>
<script>
// async function timeout(ms) {
//   await new Promise((resolve, reject) => {
//     setTimeout(reject('123'), ms);
//   });
// }
// async function asyncPrint(value, ms) {
//   try {
//     await timeout(ms);
//     console.log(value);
//   } catch (e) {
//     console.log(e);
//   }
// }

// asyncPrint('hello world', 50);

//   try {
//     let a = 0;
//     // let b = a + 'c;
//     // setTimeout(() => {
//     // undefined.map(v => v);
//     // }, 1000)
//   } catch (e) {
//     console.log(e);
//   }
  window.addEventListener('unhandledrejection', (error) => {
    console.log('unhandledrejection-error', error);
  }, true)

  // try {
  //   console.log(1);
  //   setTimeout(function(){
  //     console.log(2);
  //     throw new Error("This is a test error 2");
  //   }, 1000);
  //   console.log(3);
  // } catch(err) {
  //   console.warn(err);
  // }
  // console.log(4);

  // window.onerror = function(message, source, lineno, colno, error) {
  //   console.log('捕获到异常：',{message, source, lineno, colno, error});
  //   return true;
  // }

  // window.onunhandledrejection

  // Promise.reject('123');

//   window.onerror = function(message, source, lineno, colno, error) {
//     // message：错误信息（字符串）。
//     // source：发生错误的脚本URL（字符串）
//     // lineno：发生错误的行号（数字）
//     // colno：发生错误的列号（数字）
//     // error：Error对象（对象）
//     console.log('捕获到异常：',{message, source, lineno, colno, error});
// }

  window.onerror = function(errorMessage, scriptURI, lineNo, columnNo, error) {
      console.log('errorMessage: ' + errorMessage); // 异常信息
      console.log('scriptURI: ' + scriptURI); // 异常文件路径
      console.log('lineNo: ' + lineNo); // 异常行号
      console.log('columnNo: ' + columnNo); // 异常列号
      console.log('error: ' + error); // 异常堆栈信息
      return true; // 返回 true，异常不向上抛出、浏览器报错
  };

  window.addEventListener('error', (error) => {
    console.log('捕获到异常：', error);
  }, true)

  // setTimeout(() => {
  //   console.log(a);
  // })

  // window.addEventListener("unhandledrejection", function(e){
  //   e.preventDefault(); // 阻止异常向上抛出
  //   console.log('捕获到异常：', e);
  // });
  // Promise.reject('promise error');

  // let num = 123456;
  // num.toUpperCase();

  // let obj = new 10;
  // console.log('name' in true);

  // const arr1 = new Array(99 ** 99);
  // const arr1 = new Array(-20);

  // function test() {
  //   test();
  // }

  // test();

  // console.log(dog);

  // let cat = dog;
  // // let cat dog = '';

  // decodeURI('%');
  // encodeURI(123456);

  // try {
  //   console.log(1);
  //   setTimeout(() => {
  //   console.log(2);
  //     throw new Error('This is a test error 2');
  //   }, 1000);
  //   console.log(3);
  // } catch(error) {
  //   console.warn(error);
  // }
  // console.log(4);

  // try {
  //   // eval('aaa aaa aaa');
  //   let cat dog = '';
  // } catch (e) {
  //   console.log(e);
  // }

  const promise = new Promise((resolve, reject) => {
    if (1 + 1 > 3) {
      resolve('success');
    } else {
      reject('error');
    }
  })

  try {
    promise
      .then((res) => console.log(res))
      // .catch((err) => console.warn(err))
  } catch (err) {
    console.log(err);
  }

</script>
</html>